import type { Metadata } from "next";
import { Space_Grotesk, DM_Sans, Noto_Serif_SC } from "next/font/google";
import "./globals.css";

export const fontHeading = Space_Grotesk({
  variable: "--font-heading",
  subsets: ["latin"]
});

export const fontBody = DM_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

export const cnFont = Noto_Serif_SC({
  variable: "--font-cn",
  subsets: ["latin"], // you can also add "chinese-simplified" if available
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontHeading.className}
      >
        {children}
      </body>
    </html>
  );
}
